### ISSUE TITLE
ロゴを作りたい

### ISSUE THREAD

**Issue by chocolatina** [june29/sokuseki#116]
デザインを考えていく上で全体の指針となるような
サービスイメージを表したロゴを試しに作ってみたい

**Comment by chocolatina** [comment]
## ユーザーにしてほしいこと
自分が頑張ったログを簡単に取得してほしい

## Sokusekiと言う言葉から連想されるもの
- 足跡
- 軌跡
- ログ
- 続いていくこと
- 簡単
- 効率的
- 安心

## 結果
こんなのはどうでしょう
<img width="642" alt="スクリーンショット 2019-05-24 11 49 02" src="https://user-images.githubusercontent.com/726349/58299419-1e0e1680-7e1a-11e9-9ede-f825259a4ab7.png">

**Comment by june29** [comment]
ウワー、とてもうれしいです！ありがとうございます :relaxed:

最初見たときに純粋な感想として「この S のモチーフのスニーカーがほしい！」と思って、よく考えてみると「足跡」と「スニーカー」は意味もリンクするからすごいなって思いました :muscle:

利用したいシーンを下記にまとめます。

- HTML 内に表示するロゴ
- Favicon
- Slack に Custom Emoji として登録したい
- GitHub の org をつくるので、それ用のアイコンがほしい
- (欲張りプラン) グッズをつくりたい

なので、正方形で使えるバージョンがあると、とてもうれしいです :hugs:

**Comment by chocolatina** [comment]
ロゴファイルはこちら
https://files.slack.com/files-pri/T03GLB4LV-FJZ36P1HN/download/logo.ai
