### ISSUE TITLE
テンションの上がる見た目にしたい

### ISSUE THREAD

**Issue by june29** [june29/sokuseki#14]
現時点で、意図的に CSS をまったく書いていない。ぼくが中途半端に表示に手を入れるとデザイナさんが手を出しにくくなるだろう、と思ってノータッチでやっていきた。

いい感じの画をいっしょに考えてくれるデザイナさんがいたら巻き込みたい。

**Comment by yinm** [comment]
(デザインもできなければ、CSSもほとんど書けないのですが...！)
スタイル当てていくぞ！ってなった時に一緒に作業したいです :octocat:

**Comment by june29** [comment]
https://github.com/june29/sokuseki/pull/126 で満たされた！ここから先は少しずつ積み重ねていくフェーズに突入です :dash:
